apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-email-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: example@gmail.com 
        from: ${EMAIL_ADDRESS} # Update your from mail id here
        smarthost: smtp.gmail.com:587
        auth_username: ${EMAIL_ADDRESS} # Update your from mail id here
        auth_identity: ${EMAIL_ADDRESS} # Update your from mail id here
        auth_password: ${EMAIL_PASSWORD} # Update your app-password here
        send_resolved: true
        headers:
          subject: " Prometheus -  Alert  "
        text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "

    route:
      group_wait: 10s
      group_interval: 2m
      receiver: 'gmail-notifications'
      repeat_interval: 2m
